FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Set the working directory to where the server is located
WORKDIR /app/src

# Expose port 8000 for FastAPI
EXPOSE 8000

# Run FastAPI using Uvicorn
CMD ["uvicorn", "UI_Server_FastAPI:app", "--host", "0.0.0.0", "--port", "8000"]
