import type { Metadata } from "next";
import localFont from "next/font/local";
import Nav from "@/components/nav";
import "./globals.css";

const primary = localFont({
  src: "./fonts/AntonSC-Regular.ttf",
  variable: "--font-primary"
});

const secondary = localFont({
  src: "./fonts/GeistMono-Medium.ttf",
  variable: "--font-secondary"
});

export const fonts = {
  primary,
  secondary,
};


export const metadata: Metadata = {
  title: "StockSensAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${secondary.className} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
