import type { Metadata } from "next";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/shadcn/ui/sidebar";
import MainSidebar from "@/components/sidebar";
import { Toaster } from "@/shadcn/ui/sonner";

export const metadata: Metadata = {
  title: "StockSensAI",
  description: "Generated by create next app",
  icons: "/favicon.ico"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={'antialiased text-white'}
      >
          <SidebarProvider open={false} defaultOpen={false}>
            <MainSidebar />
            <SidebarInset>
              <article className="flex-1">
                {children}
              </article>
            </SidebarInset>
          </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
