import type { Metadata } from "next";
import Head from "next/head";
import Nav from "@/components/nav";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/shadcn/ui/sidebar";
import MainSidebar from "@/components/sidebar";


export const metadata: Metadata = {
  title: "StockSensAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={'antialiased text-white'}
      >
        <SidebarProvider defaultOpen={false}>
          <MainSidebar />
          <SidebarInset>
            <Nav />
            <article className="flex-1">
              {children}
            </article>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
