services:
  database:
    image: couchdb:latest
    restart: always
    environment:
      - COUCHDB_USER=stocksensai
      - COUCHDB_PASSWORD=ComputerEngineersGoToClass
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - "5984:5984"

  frontend:
    image: ghcr.io/ece49595-team2/stocksensai-frontend:latest
    environment:
      - NODE_ENV=development
      - COUCHDB_URL=http://database:5984
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  algorithmic-trader:
    image: ghcr.io/ECE49595-Team2/stocksensai-algorithmic:latest
    env_file:
      - ./backend/algorithmic-trader/src/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
  watchtower:
    image: containrrr/watchtower
    command: --interval 30 --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  couchdb_data: