services:
  frontend:
    image: ghcr.io/ece49595-team2/stocksensai-frontend:latest
    environment:
      - NODE_ENV=production
      - COUCHDB_URL=http://database:5984
    ports:
      - "3000:3000"
    networks:
      - external
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  algorithmic-trader:
    image: ghcr.io/ece49595-team2/stocksensai-algorithmic:latest
    secrets:
      - api_key
      - api_secret
    networks:
      - internal 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
  
  llm-server:
    image: ghcr.io/ece49595-team2/stocksensai-llm-server:latest
    networks:
      - internal
    ports:
      - "8011:8011"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  external:
    external: false
  internal: 
    external: false