services:
  database:
    image: couchdb:latest
    restart: always
    environment:
      - COUCHDB_USER=stocksensai
      - COUCHDB_PASSWORD=ComputerEngineersGoToClass
      - COUCHDB_BIND_ADDRESS=0.0.0.0
      - COUCHDB_SINGLE_NODE=true
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb_config/config.ini:/opt/couchdb/etc/local.ini
    ports:
      - "5984:5984"

  frontend:
    image: ghcr.io/ece49595-team2/stocksensai-frontend:latest
    environment:
      - NODE_ENV=development
      - COUCHDB_URL=http://database:5984
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  algorithmic-trader:
    image: ghcr.io/ECE49595-Team2/stocksensai-algorithmic:latest
    env_file:
      - ./backend/algorithmic-trader/src/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure     
  
  llm-server:
    image: ghcr.io/ece49595-team2/stocksensai-llm-server:latest
    ports:
      - "8011:8011"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  watchtower:
    image: containrrr/watchtower
    command: --interval 30 --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - frontend
      - certbot

  certbot: 
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done;'"

volumes:
  couchdb_data: