import type { Metadata } from "next";
import "../globals.css";
import DashboardSidebar from "./components/dashboard-sidebar";
import { SidebarProvider } from "@/shadcn/ui/sidebar";
import DashboardMenubar from "./components/dashboard-menubar";

export const metadata: Metadata = {
    title: "StockSensAI",
    description: "Generated by create next app",
    icons: "/favicon.ico"
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-row h-screen w-screen bg-white font-geist-mono">
            <SidebarProvider defaultOpen={true}>
                <DashboardSidebar />
                <article className="flex-1 p-4">
                    <DashboardMenubar />
                    {children}
                </article>
            </SidebarProvider>
        </div>
    );
}
