name: LLM Server Docker CI

on:
  push:
    paths:
      - "backend/llm-api/**"

jobs:

  compile_docker:
    name: Compile with Docker
    runs-on: ubuntu-latest
        
    steps:
      - name: Build with Docker
        run: docker build -t stocksensai-llm-server backend/llm-api/