name: LLM Server (Docker)

on:
  push:
    paths:
      - "backend/llm-api/**"

jobs:

  build:

    name: Compile with Docker
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ECE49595-Team2 --password-stdin

      - name: Build with Docker
        run: docker build --file ./backend/llm-api/Dockerfile --tag ghcr.io/ece49595-team2/stocksensai-llm-server:latest ./backend/llm-api/
      
      - name: Push the Docker image to GHPR
        run: docker push ghcr.io/ece49595-team2/stocksensai-llm-server:latest